"""Data models for the deep research system."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID, uuid4


def utc_now() -> datetime:
    """Get current UTC time as timezone-aware datetime."""
    return datetime.now(timezone.utc)

from pydantic import BaseModel, Field


class ResearchPhase(str, Enum):
    """Phases of the research workflow."""

    PLANNING = "planning"
    PLAN_REVIEW = "plan_review"
    RESEARCHING = "researching"
    SYNTHESIZING = "synthesizing"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class AgentStatus(str, Enum):
    """Status of an individual agent."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class PlanItemStatus(str, Enum):
    """Status of a plan item."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class PlanItem(BaseModel):
    """A single research item in the plan."""

    id: str = Field(default_factory=lambda: str(uuid4())[:8])
    topic: str = Field(..., description="Research topic or question")
    description: str = Field(..., description="Detailed description of what to research")
    scope: str = Field(default="", description="Scope boundaries for this research item")
    priority: int = Field(default=1, ge=1, le=5, description="Priority (1=highest, 5=lowest)")
    key_questions: list[str] = Field(
        default_factory=list, description="Key questions to answer"
    )
    suggested_sources: list[str] = Field(
        default_factory=list, description="Suggested sources to explore"
    )
    status: PlanItemStatus = Field(default=PlanItemStatus.PENDING)


class ResearchPlan(BaseModel):
    """A complete research plan generated by the planner agent."""

    understanding: str = Field(..., description="Planner's understanding of the query")
    clarifications: list[str] = Field(
        default_factory=list, description="Points that need clarification"
    )
    plan_items: list[PlanItem] = Field(
        default_factory=list, description="List of research items"
    )
    estimated_time_minutes: int = Field(
        default=30, description="Estimated time to complete research"
    )
    created_at: datetime = Field(default_factory=utc_now)
    modified_at: datetime = Field(default_factory=utc_now)

    def get_pending_items(self) -> list[PlanItem]:
        """Get all pending plan items."""
        return [item for item in self.plan_items if item.status == PlanItemStatus.PENDING]

    def get_item_by_id(self, item_id: str) -> PlanItem | None:
        """Get a plan item by its ID."""
        for item in self.plan_items:
            if item.id == item_id:
                return item
        return None

    def update_item_status(self, item_id: str, status: PlanItemStatus) -> bool:
        """Update the status of a plan item."""
        item = self.get_item_by_id(item_id)
        if item:
            item.status = status
            self.modified_at = utc_now()
            return True
        return False


class AgentProgress(BaseModel):
    """Progress information for a running agent."""

    agent_id: str = Field(..., description="Unique identifier for this agent")
    plan_item_id: str = Field(..., description="ID of the plan item being researched")
    topic: str = Field(..., description="Topic being researched")
    status: AgentStatus = Field(default=AgentStatus.PENDING)
    current_action: str = Field(default="", description="Current action description")
    tool_name: str | None = Field(default=None, description="Currently used tool")
    progress_percent: float = Field(
        default=0.0, ge=0.0, le=100.0, description="Progress percentage"
    )
    started_at: datetime | None = Field(default=None)
    completed_at: datetime | None = Field(default=None)
    error: str | None = Field(default=None)


class Source(BaseModel):
    """A source reference for research findings."""

    url: str | None = Field(default=None, description="URL of the source")
    title: str = Field(..., description="Title or description of the source")
    snippet: str = Field(default="", description="Relevant snippet from the source")
    reliability: str = Field(
        default="medium", description="Reliability assessment (high/medium/low)"
    )


class AgentResult(BaseModel):
    """Result from a completed researcher agent."""

    agent_id: str = Field(..., description="ID of the agent that produced this result")
    plan_item_id: str = Field(..., description="ID of the plan item researched")
    topic: str = Field(..., description="Topic that was researched")
    findings: str = Field(..., description="Main findings from the research")
    sources: list[Source] = Field(default_factory=list, description="Sources used")
    confidence: float = Field(
        default=0.8, ge=0.0, le=1.0, description="Confidence in findings (0-1)"
    )
    raw_notes: str = Field(default="", description="Raw notes from the agent")
    execution_time: float = Field(default=0.0, description="Execution time in seconds")
    created_at: datetime = Field(default_factory=utc_now)


class Checkpoint(BaseModel):
    """Checkpoint for session recovery."""

    session_id: str = Field(..., description="Session ID")
    phase: ResearchPhase = Field(..., description="Current phase")
    plan: ResearchPlan | None = Field(default=None, description="Current research plan")
    completed_agents: list[str] = Field(
        default_factory=list, description="IDs of completed agents"
    )
    agent_results: list[AgentResult] = Field(
        default_factory=list, description="Results from completed agents"
    )
    pending_agents: list[str] = Field(
        default_factory=list, description="IDs of pending agents"
    )
    checkpoint_time: datetime = Field(default_factory=utc_now)
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata"
    )


class ResearchSession(BaseModel):
    """A complete research session."""

    session_id: str = Field(
        default_factory=lambda: str(uuid4()), description="Unique session identifier"
    )
    user_query: str = Field(..., description="Original user query")
    detected_language: str = Field(default="en", description="Detected language of query")
    phase: ResearchPhase = Field(default=ResearchPhase.PLANNING)
    plan: ResearchPlan | None = Field(default=None, description="Research plan")
    agent_progress: dict[str, AgentProgress] = Field(
        default_factory=dict, description="Progress of each agent"
    )
    agent_results: list[AgentResult] = Field(
        default_factory=list, description="Results from completed agents"
    )
    final_report: str | None = Field(default=None, description="Final synthesized report")
    clarification_history: list[tuple[str, str]] = Field(
        default_factory=list, description="History of (question, answer) clarifications"
    )
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)
    completed_at: datetime | None = Field(default=None)
    error: str | None = Field(default=None, description="Error message if failed")

    def update_phase(self, phase: ResearchPhase) -> None:
        """Update the session phase."""
        self.phase = phase
        self.updated_at = utc_now()
        if phase in (ResearchPhase.COMPLETED, ResearchPhase.FAILED, ResearchPhase.CANCELLED):
            self.completed_at = utc_now()

    def add_agent_result(self, result: AgentResult) -> None:
        """Add an agent result to the session."""
        self.agent_results.append(result)
        self.updated_at = utc_now()

    def update_agent_progress(self, progress: AgentProgress) -> None:
        """Update agent progress."""
        self.agent_progress[progress.agent_id] = progress
        self.updated_at = utc_now()

    def to_checkpoint(self) -> Checkpoint:
        """Create a checkpoint from the current session state."""
        return Checkpoint(
            session_id=self.session_id,
            phase=self.phase,
            plan=self.plan,
            completed_agents=[r.agent_id for r in self.agent_results],
            agent_results=self.agent_results,
            pending_agents=[
                aid
                for aid, p in self.agent_progress.items()
                if p.status in (AgentStatus.PENDING, AgentStatus.RUNNING)
            ],
            checkpoint_time=utc_now(),
            metadata={
                "user_query": self.user_query,
                "detected_language": self.detected_language,
            },
        )

    @classmethod
    def from_checkpoint(cls, checkpoint: Checkpoint) -> "ResearchSession":
        """Restore a session from a checkpoint."""
        session = cls(
            session_id=checkpoint.session_id,
            user_query=checkpoint.metadata.get("user_query", ""),
            detected_language=checkpoint.metadata.get("detected_language", "en"),
            phase=checkpoint.phase,
            plan=checkpoint.plan,
            agent_results=checkpoint.agent_results,
        )
        return session


class StartResearchRequest(BaseModel):
    """Request to start a new research session."""

    query: str = Field(..., min_length=1, description="Research query")
    language: str | None = Field(default=None, description="Preferred language for response")


class ConfirmPlanRequest(BaseModel):
    """Request to confirm or modify a research plan."""

    confirmed: bool = Field(..., description="Whether the plan is confirmed")
    modifications: list[PlanItem] | None = Field(
        default=None, description="Modified plan items"
    )
    skip_items: list[str] | None = Field(
        default=None, description="IDs of items to skip"
    )


class ResearchSessionResponse(BaseModel):
    """Response containing session information."""

    session_id: str
    phase: ResearchPhase
    plan: ResearchPlan | None = None
    agent_progress: dict[str, AgentProgress] = Field(default_factory=dict)
    completed_agents: int = 0
    total_agents: int = 0
    final_report: str | None = None
    error: str | None = None
    created_at: datetime
    updated_at: datetime

    @classmethod
    def from_session(cls, session: ResearchSession) -> "ResearchSessionResponse":
        """Create response from a session."""
        total_agents = len(session.plan.plan_items) if session.plan else 0
        return cls(
            session_id=session.session_id,
            phase=session.phase,
            plan=session.plan,
            agent_progress=session.agent_progress,
            completed_agents=len(session.agent_results),
            total_agents=total_agents,
            final_report=session.final_report,
            error=session.error,
            created_at=session.created_at,
            updated_at=session.updated_at,
        )
